name: review_automation
on:
  issue_comment:
    types:
      - created
jobs:
  add-comment:
    if: github.event.comment.body == 'auto_review'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add code review comment
        run: gh pr comment "$NUMBER" --body "$CODE_BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          CODE_BODY: |
            ## Here is a systematic evaluation of the provided code from a TA perspective:
      - name: Add testing review comment
        run: gh pr comment "$NUMBER" --body "$TEST_BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          TEST_BODY: |
            ##Here is a systematic evaluation of the provided code from a testing perspective:
